[mcp_servers.serena]
command = "serena"
args = ["start-mcp-server", "--project-from-cwd", "--context=codex"]
startup_timeout_sec = 30

env = { SystemRoot = "C:\\Windows", PROGRAMFILES = "C:\\Program Files" }

[mcp_servers.nx-mcp]
command = "bunx"
args = [
  "nx",
  "mcp",
  "--no-minimal"
]